config/routes.rb
#                           PUT    /feedbacks/:id(.:format)                                                                 feedbacks#update
#                           DELETE /feedbacks/:id(.:format)                                                                 feedbacks#destroy
#                    orders GET    /orders(.:format)                                                                        orders#index
#                           POST   /orders(.:format)                                                                        orders#create
#                 new_order GET    /orders/new(.:format)                                                                    orders#new
#                edit_order GET    /orders/:id/edit(.:format)                                                               orders#edit
#                     order GET    /orders/:id(.:format)                                                                    orders#edit
#                           PATCH  /orders/:id(.:format)                                                                    orders#update
#                           PUT    /orders/:id(.:format)                                                                    orders#update
#                           DELETE /orders/:id(.:format)                                                                    orders#destroy
#           product_approve PUT    /products/:product_id/approve(.:format)                                                  products#approve
#            product_reject PUT    /products/:product_id/reject(.:format)                                                   products#reject
#          product_comments GET    /products/:product_id/comments(.:format)                                                 comments#index
#                           POST   /products/:product_id/comments(.:format)                                                 comments#create
#       new_product_comment GET    /products/:product_id/comments/new(.:format)                                             comments#new
#      edit_product_comment GET    /products/:product_id/comments/:id/edit(.:format)                                        comments#edit
#           product_comment GET    /products/:product_id/comments/:id(.:format)                                             comments#edit
#                           PATCH  /products/:product_id/comments/:id(.:format)                                             comments#update
#                           PUT    /products/:product_id/comments/:id(.:format)                                             comments#update
#                           DELETE /products/:product_id/comments/:id(.:format)                                             comments#destroy
#            product_orders GET    /products/:product_id/orders(.:format)                                                   orders#index
#                           POST   /products/:product_id/orders(.:format)                                                   orders#create
#         new_product_order GET    /products/:product_id/orders/new(.:format)                                               orders#new
#        edit_product_order GET    /products/:product_id/orders/:id/edit(.:format)                                          orders#edit
#             product_order GET    /products/:product_id/orders/:id(.:format)                                               orders#edit
#                           PATCH  /products/:product_id/orders/:id(.:format)                                               orders#update
#                           PUT    /products/:product_id/orders/:id(.:format)                                               orders#update
#                           DELETE /products/:product_id/orders/:id(.:format)                                               orders#destroy
#                  products GET    /products(.:format)                                                                      products#index
#                           POST   /products(.:format)                                                                      products#create
#               new_product GET    /products/new(.:format)                                                                  products#new
#              edit_product GET    /products/:id/edit(.:format)                                                             products#edit
#                   product GET    /products/:id(.:format)                                                                  products#edit
#                           PATCH  /products/:id(.:format)                                                                  products#update
#                           PUT    /products/:id(.:format)                                                                  products#update
#                           DELETE /products/:id(.:format)                                                                  products#destroy
#        product_categories GET    /product_categories(.:format)                                                            product_categories#index
#                           POST   /product_categories(.:format)                                                            product_categories#create
#      new_product_category GET    /product_categories/new(.:format)                                                        product_categories#new
#     edit_product_category GET    /product_categories/:id/edit(.:format)                                                   product_categories#edit
#          product_category GET    /product_categories/:id(.:format)                                                        product_categories#edit
#                           PATCH  /product_categories/:id(.:format)                                                        product_categories#update
#                           PUT    /product_categories/:id(.:format)                                                        product_categories#update
#                           DELETE /product_categories/:id(.:format)                                                        product_categories#destroy
#                 addresses GET    /addresses(.:format)                                                                     addresses#index
#                           POST   /addresses(.:format)                                                                     addresses#create
#               new_address GET    /addresses/new(.:format)                                                                 addresses#new
#              edit_address GET    /addresses/:id/edit(.:format)                                                            addresses#edit
#                   address GET    /addresses/:id(.:format)                                                                 addresses#edit
#                           PATCH  /addresses/:id(.:format)                                                                 addresses#update
#                           PUT    /addresses/:id(.:format)                                                                 addresses#update
#                           DELETE /addresses/:id(.:format)                                                                 addresses#destroy
#                   profile GET    /profile(.:format)                                                                       users#profile
#                     users POST   /auth/users(.:format)                                                                    users#create
#                  new_user GET    /auth/users/new(.:format)                                                                users#new
#                  sessions POST   /auth/sessions(.:format)                                                                 sessions#create
#               new_session GET    /auth/sessions/new(.:format)                                                             sessions#new
#                    logout GET    /auth/logout(.:format)                                                                   application#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#edit
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#edit
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#edit
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  root :to => "home#index"
  get "contact" => "home#new"
  post "contact" => "home#create"
  get "admin/products/" => "products#products"
  get "admin/transactions/" => "transactions#all"
  get "admin/orders/" => "orders#all"
  get "admin/users/" => "users#index"


  resources :transactions
  resources :feedbacks

  resources :orders do
    put :deliver, :to => "orders#deliver"
    put :received, :to => "orders#received"
    put :acknowledged, :to => "orders#acknowledged"
  end

  resources :products do
    put :approve, :to => "products#approve"
    put :reject, :to => "products#reject"
    resources :comments
    resources :orders
  end
  resources :product_categories
  resources :addresses

  get '/profile' => 'users#profile'
  get '/profile/edit' => 'users#edit'
  patch '/profile/edit' => 'users#update'

  scope :auth do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
    get '/logout' => 'application#destroy'
  end

  # get '*', :to => 'not_found#index!'

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  gender          :string
#  contact         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_type       :string           default("member"), not null
#

class User < ApplicationRecord
  validates :name, :email, :gender, :user_type, presence: true
  validates :email, uniqueness: true
  validates :contact, :presence => true, :numericality => true, :length => {:minimum => 10, :maximum => 15}
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates_inclusion_of :gender, :in => %w( Male Female )
  validates :password, length: {in: 6..20}, :if => :password
  has_secure_password


  has_one :address, dependent: :delete
  accepts_nested_attributes_for :address
  has_many :comments

  has_many :products

  has_many :user_buyer, :class_name => 'Order', :foreign_key => 'user_buyer_id'
  has_many :user_customer, :class_name => 'Order', :foreign_key => 'user_customer_id'

  has_many :customer_user, :class_name => 'Transaction', :foreign_key => 'customer_user_id'

  before_save :set_user_type, :unless => :user_type

  def user_country
    COUNTRIES.find {|country| country[:code] == self.address.country}
  end

  private


  def set_user_type
    self.user_type = USER_TYPES[:MEMBER]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: [:profile]
  before_action :require_login, only: [:edit, :update, :profile, :index]
  before_action :set_user, only: [:edit, :update, :profile]


  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
    address = @user.build_address
  end


  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html {redirect_to new_session_url, notice: 'User was successfully created.'}
        format.json {render :'sessions/new', status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end


  def profile

  end

  def edit
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(update_user_params)
        format.html {redirect_to profile_path(@user), notice: 'User was successfully updated.'}
        format.json {render :edit, status: :ok, location: @user}
      else
        format.html {render :'users/edit'}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html {redirect_to users_url, notice: 'User was successfully destroyed.'}
  #     format.json {head :no_content}
  #   end
  # end

  private

  def set_user
    @user = @current_user
  end

  def update_user_params
    params.require(:user).permit(:name, :gender, :contact, address_attributes: [:country, :address, :state, :postcode])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :contact, address_attributes: [:country, :address, :state, :postcode])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-md-7">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, :class => "form-control" %>
    </div>


    <div class="form-group">
      <%= form.label :gender %><br/>
      <%= form.label :gender, "Male", :value => "true" %>
      <%= form.radio_button :gender, "Male" %>
      <%= form.label :gender, "Female", :value => "false" %>
      <%= form.radio_button :gender, "Female" %>

    </div>

    <div class="form-group">
      <%= form.label :contact %>
      <%= form.text_field :contact, :class => "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
</div>

app/views/users/edit.html.erb
<div class="col-md-7">
  <h2 class="text-center">Update Information</h2>
  <div class="panel panel-default mt-20">
    <div class="panel-heading">User Information</div>
    <div class="panel-body">

      <%= form_with(model: @user, local: true, :url => {:controller => 'users', :action => :edit}) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, :class => "form-control", :readonly => true %>
        </div>


        <div class="form-group">
          <%= form.label :gender %><br/>
          <%= form.label :gender, "Male", :value => "Male" %>
          <%= form.radio_button :gender, "Male", :checked => true %>
          <%= form.label :gender, "Female", :value => "Female" %>
          <%= form.radio_button :gender, "Female" %>
        </div>

        <div class="form-group">
          <%= form.label :contact %>
          <%= form.text_field :contact, :class => "form-control" %>
        </div>

        </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Address Details</div>
          <div class="panel-body">
            <%= form.fields_for :address do |a| %>
              <div class="form-group">
                <%= a.label :address %><br/>
                <%= a.text_field :address, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= a.label :state %><br/>
                <%= a.text_field :state, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= a.label :postcode %><br/>
                <%= a.number_field :postcode, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= a.label :country %><br/>
                <%= a.select(:country, options_for_select(COUNTRIES.map {|country| [country[:name], country[:code]]}), {}, {:class => "form-control"}) %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="actions pull-right">
          <%= form.submit 'Update Details', :class => 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
      </div>

app/views/users/index.html.erb
<div class="col-md-7">
  <p id="notice"><%= notice %></p>

  <h1>Users List</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Contact</th>
      <th>Address</th>
      <th>State</th>
      <th>Postcode</th>

    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.user_type %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.contact %></td>
        <td><%= user.address.address %></td>
        <td><%= user.address.state %></td>
        <td><%= user.address.postcode %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%#= link_to 'New User', new_user_path %>
</div>

app/views/users/login.html.erb
<div class="col-md-7">
  <h1 class="text-center">Welcome to login</h1>
  <%= form_for @user, url: {action: "login"}, html: {class: "nifty_form"} do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="text-center">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, :class => 'form-control' %>
    </div>

    <div class="pull-right">
      <%= form.submit 'Login', :class => 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
</div>

app/views/users/new.html.erb
<div class="col-md-7">
<h2 class="text-center">Register New User</h2>
<div class="panel panel-default mt-20">
  <div class="panel-heading">User Information</div>
  <div class="panel-body">

    <%= form_with(model: @user, local: true) do |form| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, :class => "form-control" %>
      </div>

      <div class="field form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :gender %><br/>
        <%= form.label :gender, "Male", :value => "Male" %>
        <%= form.radio_button :gender, "Male", :checked => true %>
        <%= form.label :gender, "Female", :value => "Female" %>
        <%= form.radio_button :gender, "Female" %>
      </div>

      <div class="form-group">
        <%= form.label :contact %>
        <%= form.text_field :contact, :class => "form-control" %>
      </div>

      </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Address Details</div>
        <div class="panel-body">
          <%= form.fields_for :address do |a| %>
            <div class="form-group">
              <%= a.label :address %><br/>
              <%= a.text_area :address, :class => "form-control" %>
            </div>

            <div class="form-group">
              <%= a.label :state %><br/>
              <%= a.text_field :state, :class => "form-control" %>
            </div>

            <div class="form-group">
              <%= a.label :postcode %><br/>
              <%= a.number_field :postcode, :class => "form-control" %>
            </div>

            <div class="form-group">
              <%= a.label :country %><br/>
              <%= a.select(:country, options_for_select(COUNTRIES.map {|country| [country[:name], country[:code]]}), {}, {:class => "form-control"}) %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="actions pull-right">
        <%= form.submit 'Register', :class => 'btn btn-primary' %>
      </div>
    <% end %>
    <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
    </div>

app/views/users/profile.html.erb
<div class="col-md-10">
  <div class="panel panel-info">
    <div class="panel-heading">
      User Profile Details
    </div>
    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <div class="col-md-4 mb-5">
        <h4 class="card-title"><b>User Name:</b> <%= @user.name.humanize %></h4>
        <p>
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <p>
          <strong>Gender:</strong>
          <%= @user.gender %>
        </p>

        <p>
          <strong>Contact:</strong>
          <%= @user.contact %>
        </p>

        <p>
          <strong>Role:</strong>
          <%= @user.user_type %>
        </p>
      </div>
    </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      Address Details
    </div>
    <div class="panel-body">
      <div class="col-md-4 mb-5">
        <p>
          <strong>Address:</strong>
          <%= @user.address.address %>
        </p>

        <p>
          <strong>State:</strong>
          <%= @user.address.state %>
        </p>

        <p>
          <strong>Postcode:</strong>
          <%= @user.address.postcode %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @user.user_country[:name] %>
        </p>
      </div>
    </div>
  </div>
  <%= link_to 'Edit Profile', profile_edit_path, :class => 'btn btn-primary', data: {turbolinks: false} %>
</div>